/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.*;
import javax.swing.JPanel;

/**
 *
 * @author juand
 */
public class registro extends javax.swing.JFrame {

    String vacio = "";

    public registro() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        volver = new javax.swing.JPanel();
        volverLabel = new javax.swing.JLabel();
        azul = new javax.swing.JPanel();
        cc_registro = new javax.swing.JTextField();
        nombre_registro1 = new javax.swing.JTextField();
        clave_registro = new javax.swing.JTextField();
        confirma_clave = new javax.swing.JTextField();
        panelCrearUsuario = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        x = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(335, 340));
        setSize(new java.awt.Dimension(395, 340));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        volver.setBackground(new java.awt.Color(51, 153, 255));
        volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                volverMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                volverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                volverMouseExited(evt);
            }
        });
        volver.setLayout(new java.awt.GridBagLayout());

        volverLabel.setForeground(new java.awt.Color(255, 255, 255));
        volverLabel.setText("🢀");
        volverLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                volverLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                volverLabelMouseExited(evt);
            }
        });
        volver.add(volverLabel, new java.awt.GridBagConstraints());

        getContentPane().add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        azul.setBackground(new java.awt.Color(51, 153, 255));

        javax.swing.GroupLayout azulLayout = new javax.swing.GroupLayout(azul);
        azul.setLayout(azulLayout);
        azulLayout.setHorizontalGroup(
            azulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 397, Short.MAX_VALUE)
        );
        azulLayout.setVerticalGroup(
            azulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(azul, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        cc_registro.setForeground(new java.awt.Color(51, 153, 255));
        cc_registro.setText("Número de cédula");
        cc_registro.setPreferredSize(new java.awt.Dimension(125, 25));
        cc_registro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cc_registroMouseEntered(evt);
            }
        });
        getContentPane().add(cc_registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 190, -1));

        nombre_registro1.setForeground(new java.awt.Color(51, 153, 255));
        nombre_registro1.setText("Nombres y apellidos");
        nombre_registro1.setPreferredSize(new java.awt.Dimension(125, 25));
        nombre_registro1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nombre_registro1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nombre_registro1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nombre_registro1MouseExited(evt);
            }
        });
        nombre_registro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombre_registro1ActionPerformed(evt);
            }
        });
        getContentPane().add(nombre_registro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 190, -1));

        clave_registro.setForeground(new java.awt.Color(51, 153, 255));
        clave_registro.setText("Contraseña");
        clave_registro.setPreferredSize(new java.awt.Dimension(125, 25));
        clave_registro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clave_registroMouseEntered(evt);
            }
        });
        getContentPane().add(clave_registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 190, -1));

        confirma_clave.setForeground(new java.awt.Color(51, 153, 255));
        confirma_clave.setText("Confirmación");
        confirma_clave.setPreferredSize(new java.awt.Dimension(125, 25));
        confirma_clave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                confirma_claveMouseEntered(evt);
            }
        });
        getContentPane().add(confirma_clave, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 190, -1));

        panelCrearUsuario.setBackground(new java.awt.Color(51, 153, 255));
        panelCrearUsuario.setPreferredSize(new java.awt.Dimension(397, 30));
        panelCrearUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelCrearUsuarioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelCrearUsuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelCrearUsuarioMouseExited(evt);
            }
        });
        panelCrearUsuario.setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Crear usuario");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 24, 8, 29);
        panelCrearUsuario.add(jLabel2, gridBagConstraints);

        getContentPane().add(panelCrearUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 120, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 153, 255));
        jLabel1.setText("REGISTRO DE NUEVO USUARIO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        javax.swing.GroupLayout xLayout = new javax.swing.GroupLayout(x);
        x.setLayout(xLayout);
        xLayout.setHorizontalGroup(
            xLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        xLayout.setVerticalGroup(
            xLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        getContentPane().add(x, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, -1, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombre_registro1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nombre_registro1MouseClicked
        nombre_registro1.setText("");
    }//GEN-LAST:event_nombre_registro1MouseClicked

    private void nombre_registro1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nombre_registro1MouseEntered

    }//GEN-LAST:event_nombre_registro1MouseEntered

    private void cc_registroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cc_registroMouseEntered
        cc_registro.setText("");
    }//GEN-LAST:event_cc_registroMouseEntered

    private void clave_registroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clave_registroMouseEntered
        clave_registro.setText("");
    }//GEN-LAST:event_clave_registroMouseEntered

    private void confirma_claveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirma_claveMouseEntered
        confirma_clave.setText("");
    }//GEN-LAST:event_confirma_claveMouseEntered

    private void nombre_registro1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nombre_registro1MouseExited
        String nombre = nombre_registro1.getText();
        if (nombre.equals(vacio)) {
            nombre_registro1.setText("Nombres y apellidos");

        }
    }//GEN-LAST:event_nombre_registro1MouseExited

    private void nombre_registro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombre_registro1ActionPerformed

    }//GEN-LAST:event_nombre_registro1ActionPerformed

    private void panelCrearUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCrearUsuarioMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_panelCrearUsuarioMouseClicked

    private void panelCrearUsuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCrearUsuarioMouseEntered
        panelCrearUsuario.setBackground(new Color(50, 173, 255));
    }//GEN-LAST:event_panelCrearUsuarioMouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited

    }//GEN-LAST:event_jLabel2MouseExited

    private void panelCrearUsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCrearUsuarioMouseExited
        panelCrearUsuario.setBackground(new Color(51, 153, 255));
    }//GEN-LAST:event_panelCrearUsuarioMouseExited

    private void volverLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverLabelMouseEntered
    }//GEN-LAST:event_volverLabelMouseEntered

    private void volverLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverLabelMouseExited
         volverLabel.setBackground(new Color(51, 153, 255));    }//GEN-LAST:event_volverLabelMouseExited

    private void volverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverMouseEntered
        volver.setBackground(new Color(50, 173, 255));
    }//GEN-LAST:event_volverMouseEntered

    private void volverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverMouseExited
        volver.setBackground(new Color(51, 153, 255));
    }//GEN-LAST:event_volverMouseExited

    private void volverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverMouseClicked
        login Login =new login();
        Login.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_volverMouseClicked

    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel azul;
    private javax.swing.JTextField cc_registro;
    private javax.swing.JTextField clave_registro;
    private javax.swing.JTextField confirma_clave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField nombre_registro1;
    private javax.swing.JPanel panelCrearUsuario;
    private javax.swing.JPanel volver;
    private javax.swing.JLabel volverLabel;
    private javax.swing.JPanel x;
    // End of variables declaration//GEN-END:variables
}
